trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Check if the gradlew script exists
    if [ ! -f "gradlew" ]; then
        echo "gradlew script not found. Generating it..."
        ./gradle wrapper
    fi
  displayName: 'Check and Generate gradlew Script'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
