trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Check if the gradlew script exists
    if [ ! -f "gradlew" ]; then
        echo "gradlew script not found. Generating it..."
        gradle wrapper # Generate Gradle Wrapper files
    fi
  displayName: 'Check and Generate gradlew Script'
  workingDirectory: $(System.DefaultWorkingDirectory)  # Set the working directory to the root of your Gradle project

- script: |
    # Ensure Gradle Wrapper is executable
    chmod +x gradlew
    # Build the project using the Gradle Wrapper
    ./gradlew build
  displayName: 'Build with Gradle'
  workingDirectory: $(System.DefaultWorkingDirectory)  # Set the working directory to the root of your Gradle project

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/build/test-results'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build/libs'
    artifactName: 'drop'
