trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '11'
    addToPath: true

- script: |
    # Ensure Gradle Wrapper is executable
    chmod +x gradlew
    # Build the project using the Gradle Wrapper
    ./gradlew build
  displayName: 'Build with Gradle'
  workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/build/test-results'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build/libs'
    artifactName: 'drop'
